# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output ./output
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.8
      with:
        # Name of the Azure Function App
        app-name: BattlesnakeFunction
        # Path to package or folder. *.zip or a folder to deploy

        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

        publish-profile:  ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        # Automatically look up Java function app artifact from pom.xml (default: 'false'). When this is set to 'true', 'package' should point to the folder of host.json.
        respect-pom-xml: false
        # Remove unwanted files defined in .funcignore file (default: 'false'). When this is set to 'true', 'package' should point to the folder of host.json.
        respect-funcignore:  false
        # Enable build action from Kudu when the package is deployed onto the function app. This will temporarily change the SCM_DO_BUILD_DURING_DEPLOYMENT setting for this deployment. To bypass this and use the existing settings from your function app, please set this to an empty string ''. To enable remote build for your project, please set this and 'enable-oryx-build' both to 'true'. By default, GitHub Action respects the packages resolved in GitHub workflow, disabling the redundant build action from Kudu endpoint. (default: 'false').
        scm-do-build-during-deployment: false
        enable-oryx-build: false
